services:
  # garage:
  #   image: dxflrs/garage:v1.0.0
  #   network_mode: "host"
  #   restart: unless-stopped
  #   volumes:
  #     - ./garage/garage.toml:/etc/garage.toml
  #     - ./data/meta:/data/garage/meta
  #     - ./data/meta:/data/garage/data

  imageresizer:
    build: ./imageResizer
    env_file: .env
    networks:
      - kebaberiie

  redis:
    image: redis:latest
    volumes: 
     - redis_vol:/data
    command: "--save 30 1"
    env_file: .env
    networks:
      - kebaberiie

  web:
    build: ./web
    # ports:
      # - 8080:8080
    env_file: .env
    networks:
      - kebaberiie
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.kebaberiie.rule=Host(`kebaberiie.56k.ing`)
      - traefik.http.routers.kebaberiie.service=kebaberiie
      - traefik.http.services.kebaberiie.loadbalancer.server.port=8080 

  postgres:
    image: postgres
    env_file: .env
    volumes:
      - postgres_vol:/var/lib/postgresql/data
      - ./bdd_sql:/docker-entrypoint-initdb.d/

    networks:
      - kebaberiie

  # adminer:
  #   image: adminer
  #   ports:
  #     - 6565:8080

volumes:
  redis_vol:
  postgres_vol:

networks:
  kebaberiie:
  traefik:
    external: true