version: "3"
services:
  garage:
    image: dxflrs/garage:v1.0.0
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - :/etc/garage.toml
      - ./data/meta:/data/garage/meta
      - ./data/meta:/data/garage/data
  imageresizer:
    build: ./imageResizer

