services:
  garage:
    image: dxflrs/garage:v1.0.0
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
      - ./data/meta:/data/garage/meta
      - ./data/meta:/data/garage/data
  imageresizer:
    build: ./imageResizer

  redis:
    image: redis:latest
    volumes: 
     - redis_vol:/data
    command: "--save 30 1"

volumes:
  redis_vol: