--- FICHIER CONTENANT LES DÉFINITIONS DES TABLES

CREATE TABLE IF NOT EXISTS Restaurant(
    id SERIAL PRIMARY KEY NOT NULL,
    nom VARCHAR(40) NOT NULL,
    adresse VARCHAR(200) NOT NULL,
    code_postal VARCHAR(40),
    site_web VARCHAR(255),
    url_photo VARCHAR(255),
    prix FLOAT
);


CREATE TABLE IF NOT EXISTS Avis(
    id SERIAL PRIMARY KEY  NOT NULL,
    restaurant INT REFERENCES Restaurant(id) NOT NULL,
    commentaire VARCHAR(500) NOT NULL,
	note INT NOT NULL,
    url_photo VARCHAR(255)
);
