--- FICHIER CONTENANT LES DÉFINITIONS DES TABLES

DROP TABLE Restaurant;
DROP TABLE Avis;



CREATE TABLE IF NOT EXISTS Restaurant(
    nom VARCHAR(40) PRIMARY KEY NOT NULL,
    adresse VARCHAR(200) NOT NULL,
    code_postal VARCHAR(40),
    site_web VARCHAR(60),
    url_photo VARCHAR(200)
);


CREATE TABLE IF NOT EXISTS Avis(
    id SERIAL PRIMARY KEY NOT NULL,
    restaurant VARCHAR(40) REFERENCES Restaurant(nom) NOT NULL,
    commentaire VARCHAR(500) NOT NULL,
	note INT NOT NULL,
    url_photo VARCHAR(200)
);
