metadata_dir = "/data/garage/meta"
data_dir = "/data/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "7551be1b954094854413b33a3173b7945ecb1fcf4e754cb3ad42f71aa9d21bea"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".s3-web.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "BfXZGl2SHjq8yJzKGlXiBu9fgFP4jprMOEa5K8X/Cog="
metrics_token = "KwiRcmBeNb+4ML1/TjhFHsJaI+OMX5uQcbkJM57HncE="
